---
title: Your awesome title
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: gregelisara@protonmail.com
description: This site is helping me learn how to create static websites using Jekyll
  and Siteleaf.
baseurl: 
url: http://yourdomain.com
twitter_username: gregelisara
github_username: quipu
markdown: kramdown
